name: Docker Image Rebuilding
on:
  push:
    branches: [ master ]
jobs:
  compile:
    name: Build and run the container
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: username/container
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: username/container:latest
          options: -v ${{ github.workspace }}:/data
          run: |
            echo "Love you Mom!"
